'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
export default function VerifyPage() {
  const router = useRouter(); const [phoneNumber, setPhoneNumber] = useState(''); const [code, setCode] = useState(''); const [developmentOtp, setDevelopmentOtp] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { setPhoneNumber(sessionStorage.getItem('talent_phone_number') || ''); setDevelopmentOtp(sessionStorage.getItem('talent_development_otp') || ''); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); const response = await fetch('/api/auth/student/verify-otp', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ phoneNumber, code }) }); setBusy(false); if (!response.ok) { const result = (await response.json()) as { error?: { message?: string } }; setError(result.error?.message || 'Код баталгаажуулахад алдаа гарлаа.'); return; } sessionStorage.removeItem('talent_development_otp'); router.push('/student'); router.refresh(); };
  return <main className="app-page relative flex min-h-screen items-center justify-center overflow-hidden px-6"><div aria-hidden="true" className="soft-float absolute -left-20 top-10 size-72 rounded-full bg-indigo-100/60 blur-3xl" /><form onSubmit={submit} className="surface enter relative w-full max-w-md rounded-3xl p-7 md:p-9"><div aria-hidden="true" className="mx-auto flex size-14 items-center justify-center rounded-2xl bg-indigo-100 text-2xl">✓</div><h1 className="mt-5 text-center text-3xl font-bold text-slate-900">Код баталгаажуулах</h1><p className="mt-2 text-center text-slate-500">{phoneNumber || 'Утасны дугаар олдсонгүй'}</p>{developmentOtp && <p className="notice-enter mt-5 rounded-xl border border-amber-100 bg-amber-50 p-3 text-center text-sm text-amber-800">Хөгжүүлэлтийн код: <strong>{developmentOtp}</strong></p>}<label className="mt-6 block text-center text-sm font-medium text-slate-700">6 оронтой код<input required aria-label="Зургаан оронтой баталгаажуулах код" value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, '').slice(0, 6))} inputMode="numeric" autoComplete="one-time-code" placeholder="000000" className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-4 text-center text-3xl font-bold tracking-[0.35em] outline-none focus:border-indigo-500" /></label>{error && <p role="alert" className="notice-enter mt-4 rounded-xl border border-red-100 bg-red-50 p-3 text-center text-sm text-red-700">{error}</p>}<button disabled={busy || !phoneNumber || code.length !== 6} className="mt-5 w-full rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white shadow-sm hover:scale-[1.01] hover:bg-indigo-700 hover:shadow-md disabled:bg-slate-300">{busy ? 'Шалгаж байна…' : 'Нэвтрэх'}</button></form></main>;
}
